acme_upload:
    resource: "@AcmeUploadBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: @AppBundle/Controller/
    type:     annotation
logout:
    path:   /logout	